/*
 * Please do not edit this file (except where indicated).
 * It was generated using rpcgen.
 */

/* Start of manually edited area */
#ifndef AES_CDH_RPC_H
#define	AES_CDH_RPC_H

#include <windows.h>
#include <d32-rpc.h>

#ifdef __cplusplus
extern "C" {
#endif
/* End of manually edited area */

#define AES_IFO_OK 0
#define AES_IFO_NOK 1
#define AES_IFO_NOT_SENT 0
#define AES_IFO_MAYBE_SENT 1
#define AES_IFO_FILE_NAME_SIZE 512
#define AES_IFO_BLOCK_SIZE 32768

struct AES_IFO_BLOCK {
	char *mainfile_name;
	u_long subfile_no;
	u_long record_no;
	u_long maxsize;
	u_long sent_indicator;
	struct {
		u_int block_len;
		char *block_val;
	} block;
};
typedef struct AES_IFO_BLOCK AES_IFO_BLOCK;
BOOL WINAPI xdr_AES_IFO_BLOCK(XDR *,AES_IFO_BLOCK *);


#define AES_IFO_PROG ((u_long)0x2df001f0)
#define AES_IFO_VERS ((u_long)1)
#define AES_IFO_OutPut ((u_long)1)
int aes_ifo_output_1 (AES_IFO_BLOCK *, u_long *, void *);

/* Start of manually edited area */
#define BGW_RPC_PROG_NUMBER 0x2df001f1
/* End of manually edited area */

enum answerCode {
	HANDLED = 0,
	UNHANDLED = 1,
};
typedef enum answerCode answerCode;
BOOL WINAPI xdr_answerCode(XDR *,answerCode *);


struct lastTransactionAnswer {
	answerCode code;
	u_long lastTransactionID;
};
typedef struct lastTransactionAnswer lastTransactionAnswer;
BOOL WINAPI xdr_lastTransactionAnswer(XDR *,lastTransactionAnswer *);


struct BlockInfo {
	char *theSourceID;
	u_long theBlockID;
	struct {
		u_int theBlockData_len;
		u_char *theBlockData_val;
	} theBlockData;
};
typedef struct BlockInfo BlockInfo;
BOOL WINAPI xdr_BlockInfo(XDR *,BlockInfo *);


typedef char *NewString;
BOOL WINAPI xdr_NewString(XDR *,NewString *);


#define BGW_CDRB_RECEIVER ((u_long)BGW_RPC_PROG_NUMBER)
#define A ((u_long)1)
#define LASTTRANSACTION ((u_long)1)
int lasttransaction_1 (NewString *, lastTransactionAnswer *, void *);
#define PUT ((u_long)2)
int put_1 (BlockInfo *, answerCode *, void *);


/* used by server stub */
int server_proc (int);

/* Start of manually edited area */
#ifdef __cplusplus
}
#endif

#endif /* AES_CDH_RPC_H */
/* End of manually edited area */
