/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "engine/rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
lasttransaction_1(char **argp, lastTransactionAnswer *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, LASTTRANSACTION,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_lastTransactionAnswer, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
put_1(BlockInfo *argp, answerCode *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, PUT,
		(xdrproc_t) xdr_BlockInfo, (caddr_t) argp,
		(xdrproc_t) xdr_answerCode, (caddr_t) clnt_res,
		TIMEOUT));
}
