/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../inc/engine/rpc.h"

bool_t
xdr_answerCode (XDR *xdrs, answerCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lastTransactionAnswer (XDR *xdrs, lastTransactionAnswer *objp)
{
	register int32_t *buf;

	 if (!xdr_answerCode (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->lastTransactionID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BlockInfo (XDR *xdrs, BlockInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->theSourceID, ~0))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->theBlockID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->theBlockData.theBlockData_val, (u_int *) &objp->theBlockData.theBlockData_len, ~0,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}
