/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "aes_cdh_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

u_long *
aes_ifo_output_1(struct AES_IFO_BLOCK *argp, CLIENT *clnt)
{
	static u_long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AES_IFO_OutPut,
		(xdrproc_t) xdr_AES_IFO_BLOCK, (caddr_t) argp,
		(xdrproc_t) xdr_u_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

lastTransactionAnswer *
lasttransaction_1(NewString *argp, CLIENT *clnt)
{
	static lastTransactionAnswer clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LASTTRANSACTION,
		(xdrproc_t) xdr_NewString, (caddr_t) argp,
		(xdrproc_t) xdr_lastTransactionAnswer, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

answerCode *
put_1(BlockInfo *argp, CLIENT *clnt)
{
	static answerCode clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PUT,
		(xdrproc_t) xdr_BlockInfo, (caddr_t) argp,
		(xdrproc_t) xdr_answerCode, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
