/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "aes_cdh_rpc.h"

bool_t
xdr_AES_IFO_BLOCK (XDR *xdrs, AES_IFO_BLOCK *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_string (xdrs, &objp->mainfile_name, AES_IFO_FILE_NAME_SIZE))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->subfile_no))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->record_no))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->maxsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->sent_indicator))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->subfile_no);
		IXDR_PUT_U_LONG(buf, objp->record_no);
		IXDR_PUT_U_LONG(buf, objp->maxsize);
		IXDR_PUT_U_LONG(buf, objp->sent_indicator);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->block.block_val, (u_int *) &objp->block.block_len, AES_IFO_BLOCK_SIZE))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_string (xdrs, &objp->mainfile_name, AES_IFO_FILE_NAME_SIZE))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_long (xdrs, &objp->subfile_no))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->record_no))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->maxsize))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->sent_indicator))
				 return FALSE;

		} else {
		objp->subfile_no = IXDR_GET_U_LONG(buf);
		objp->record_no = IXDR_GET_U_LONG(buf);
		objp->maxsize = IXDR_GET_U_LONG(buf);
		objp->sent_indicator = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->block.block_val, (u_int *) &objp->block.block_len, AES_IFO_BLOCK_SIZE))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_string (xdrs, &objp->mainfile_name, AES_IFO_FILE_NAME_SIZE))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->subfile_no))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->record_no))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->maxsize))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->sent_indicator))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->block.block_val, (u_int *) &objp->block.block_len, AES_IFO_BLOCK_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_answerCode (XDR *xdrs, answerCode *objp)
{
//	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lastTransactionAnswer (XDR *xdrs, lastTransactionAnswer *objp)
{
//	register int32_t *buf;

	 if (!xdr_answerCode (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->lastTransactionID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_BlockInfo (XDR *xdrs, BlockInfo *objp)
{
//	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->theSourceID, ~0))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->theBlockID))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->theBlockData.theBlockData_val, (u_int *) &objp->theBlockData.theBlockData_len, ~0,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NewString (XDR *xdrs, NewString *objp)
{
	//register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}
